# Generated by Django 5.1.2 on 2024-11-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_leitor_cidade_autor_editora_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='')),
                ('telefone', models.CharField(default=0)),
                ('cpf', models.IntegerField(default=0)),
                ('data_nasc', models.DateField(default='2000-01-01')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
        migrations.AddField(
            model_name='autor',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nasc',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='autor',
            name='telefone',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='editora',
            name='cnpj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='editora',
            name='razao_social',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='editora',
            name='telefone',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
