# Generated by Django 5.1.2 on 2024-11-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_autor_data_nasc_alter_editora_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
    ]
