# Generated by Django 5.1.2 on 2024-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_autor_cidade_alter_editora_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_dev',
            field=models.DateField(null=True, verbose_name='Data de Devolucao'),
        ),
    ]
